### ISSUE TITLE
How the hell do you screen lock and where is the gamepad codex thing

### ISSUE THREAD

**Issue by someguythe1st** [Ilyaki/TerrariaSplitScreen#4]
I have no idea where any of these things actually are I need help pls ples pleas.

**Comment by Ilyaki** [comment]
When you join/host a server, a menu will popup where you can select your gamepad index, e.g. One, Two, Three, Four, or None(if you want to use a keyboard+mouse). 

If you select None, you will then select a keyboard and then select a mouse. You will also be asked whether or not to lock the mouse. Click Yes if this is the last player/window, and No otherwise. You may notice that if you click No, that player's mouse will be frozen until the final player clicks Yes.

**Comment by someguythe1st** [comment]
Thank you I only recently figured this out because I thought the stuff you
were talking about was in the options and then I did it and the menu popped
up.
